files: |
  (?x)^(
    skni_site_backend/|
    skni_site_frontend/|
  )
exclude: |
  (?x)(
    .*/migrations/|
    skni_site_frontend/node_modules/|
    .*svg
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        types: [ yaml ]
      - id: check-toml
        types: [ toml ]
      - id: check-docstring-first
        exclude: skni_site_backend/gunicorn.conf.py
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - name: skni_site_backend linting
        id: ruff
        args: [ --config=skni_site_backend/pyproject.toml, --fix ]
        files: ^skni_site_backend/
      - name: skni_site_backend formatting
        id: ruff-format
        args: [ --config=skni_site_backend/pyproject.toml ]
        files: ^skni_site_backend/
  - repo: local
    hooks:
      - name: skni_site_frontend install dependencies
        id: ui-install
        entry: bash -c "cd skni_site_frontend && npm install"
        files: ^skni_site_frontend/
        language: system
      - name: skni_site_frontend linting
        id: ui-lint
        entry: bash -c "cd skni_site_frontend && npm install npm lint-staged"
        files: ^skni_site_frontend/
        language: system
      - name: skni_site_frontend type checking
        id: ui-type-check
        entry: bash -c "cd skni_site_frontend && npm run type-check"
        files: ^skni_site_frontend/
        language: system
