# Generated by Django 5.1.5 on 2025-07-08 19:59

import backend.utils.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='alt',
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, storage=backend.utils.storage.OptimizedImageStorage(base_url='/media/', format='JPEG', location=pathlib.PureWindowsPath('C:/Users/Konrad/PycharmProjects/SKNISite/skni_site_backend/media'), max_height=1200, max_width=1200, quality=85), upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(storage=backend.utils.storage.OptimizedImageStorage(base_url='/media/', format='JPEG', location=pathlib.PureWindowsPath('C:/Users/Konrad/PycharmProjects/SKNISite/skni_site_backend/media'), max_height=1200, max_width=1200, quality=85), upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=backend.utils.storage.OptimizedImageStorage(base_url='/media/', format='JPEG', location=pathlib.PureWindowsPath('C:/Users/Konrad/PycharmProjects/SKNISite/skni_site_backend/media'), max_height=1200, max_width=1200, quality=85), upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(storage=backend.utils.storage.OptimizedImageStorage(base_url='/media/', format='JPEG', location=pathlib.PureWindowsPath('C:/Users/Konrad/PycharmProjects/SKNISite/skni_site_backend/media'), max_height=1200, max_width=1200, quality=85), upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(storage=backend.utils.storage.OptimizedImageStorage(base_url='/media/', format='PNG', location=pathlib.PureWindowsPath('C:/Users/Konrad/PycharmProjects/SKNISite/skni_site_backend/media'), max_height=600, max_width=600, quality=90), upload_to='sponsors/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=backend.utils.storage.OptimizedImageStorage(base_url='/media/', format='JPEG', location=pathlib.PureWindowsPath('C:/Users/Konrad/PycharmProjects/SKNISite/skni_site_backend/media'), max_height=300, max_width=300, quality=85), upload_to='avatars/'),
        ),
    ]
